### ISSUE TITLE
broken images in assignment

### ISSUE THREAD

**Issue by bnroths** [uchicago-mobi/MPCS51032-2017-Spring-Forum#19]
I noticed that there are some broken images in the assignment description here: http://uchicago.mobi/sessions/session4/ @tabinks is it possible to fix them?

**Comment by bnroths** [comment]
ahh saw the images are showing up on this page http://uchicago.mobi/sessions/session3/ so we're probably good here :)

**Comment by tabinks** [comment]
Sorry.  I'll fix those when I get in front on a computer.
