### ISSUE TITLE
Case Study Requirements

### ISSUE THREAD

**Issue by imweihuang** [uchicago-mobi/MPCS51032-2017-Spring-Forum#22]
Hi @tabinks 
One of the case study requirements is "Submit a pull-request to the author", I can't recall the comments on this one. Does it mean we need to push a code improvement to the author? Can you provide some details? Thanks!

**Comment by tabinks** [comment]
The pull request can be anything:
* Code suggestion/improvements
* File an issue that you encountered
* Contribute to any documentation that the author provides
* Add you sample project to a list of tutorial pages
* and so ..

Basically, you should interact with the project in some what that may contribute to the project.  In the past, students have often updated the install instructions (as those are usually not updated).
