### ISSUE TITLE
Slides for Tonight

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/MPCS51032-2017-Spring-Forum#25]
Slides link: https://github.com/uchicago-mobi/uchicago-mobi.github.io/raw/master/sessions/session7/MPCS51032-2017-Spring-Lecture7.pdf

**Comment by imweihuang** [comment]
Hi @tabinks, the link to the slide is broken, could you please fix this? thanks!

**Comment by imweihuang** [comment]
Never mind, just found a working link here: http://uchicago.mobi/sessions/session7/MPCS51032-2017-Spring-Lecture7.pdf
