### ISSUE TITLE
Assignment 5 Repo

### ISSUE THREAD

**Issue by dan-olsn** [uchicago-mobi/MPCS51032-2017-Spring-Forum#28]
Hi @tabinks, is there a GitHub classroom repo set up for assignment 5?

**Comment by tabinks** [comment]
https://classroom.github.com/assignment-invitations/1a5d21c85db10e75b30b69b559cefa71

**Comment by tabinks** [comment]
@dfaoj

**Comment by dan-olsn** [comment]
Thanks
