### ISSUE TITLE
Class Notes

### ISSUE THREAD

**Issue by bnroths** [uchicago-mobi/MPCS51032-2017-Spring-Forum#31]
Can you post the notes from Monday?  I wanted to make sure I have the due dates and meeting dates down correctly for the final project.

**Comment by tabinks** [comment]
* https://github.com/uchicago-mobi/uchicago-mobi.github.io/blob/master/sessions/session8/MPCS51032-2017-Spring-Lecture8.pdf
* https://github.com/uchicago-mobi/uchicago-mobi.github.io/blob/master/sessions/session8/2017-Spring-FinalProjectRequirements.pdf

**Comment by dan-olsn** [comment]
I'm getting a 404 error for both of these links

**Comment by bnroths** [comment]
I got these ones to work
http://uchicago.mobi/sessions/session8/MPCS51032-2017-Spring-Lecture8.pdf
http://uchicago.mobi/sessions/session8/2017-Spring-FinalProjectRequirements.pdf

**Comment by tabinks** [comment]
Sorry.  I'll fix them later today.  There are direct links in one of the
issues.

**Comment by tabinks** [comment]
The links in forum are same as here.  Thanks.

**Comment by dan-olsn** [comment]
Thank you!
